# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Human readable task name
name: Playbook
# Long form description.
description: |+
  Seamlessly initiate pre-approved, strategically aligned commands with unprecedented agility.
# The flag
flag: CTF{Stand4rdizedOper4t1onalPwningSyn7ax}
# Task category. (one of hw, crypto, pwn, rev, web, net, misc)
category: pwn
# === the fields below will be filled by SRE or automation ===
# Task label
label: ''
# URL for web challenges
link: ''
# the URL for attachments, to be filled in by automation
attachment: ''
# is this challenge released? Will be set by SREs
visible: true
host: 'playbook.2025.ctfcompetition.com 1337'
