apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ctf-daemon-gcsfuse
  namespace: kube-system
  labels:
    k8s-app: ctf-daemon-gcsfuse
spec:
  selector:
    matchLabels:
      name: ctf-daemon-gcsfuse
  template:
    metadata:
      labels:
        name: ctf-daemon-gcsfuse
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: ctf-daemon
        image: ubuntu:19.10
        securityContext:
          privileged: true
        command: ["sh", "-c", "apt-get update && apt-get install -y wget fuse && wget -q https://github.com/GoogleCloudPlatform/gcsfuse/releases/download/v0.29.0/gcsfuse_0.29.0_amd64.deb && dpkg -i gcsfuse_0.29.0_amd64.deb && mkdir -p /mnt/disks/gcs && ((test -f /config/gcs_bucket && gcsfuse --foreground --debug_fuse --debug_gcs --stat-cache-ttl 0 -type-cache-ttl 0 -o allow_other -o nonempty --file-mode 0777 --dir-mode 0777 --uid 1000 --gid 1000 --key-file=$(ls /secrets/*.json|head -n 1) $(cat /config/gcs_bucket) /mnt/disks/gcs))"]
        volumeMounts:
        - name: mnt-disks-gcs
          mountPath: /mnt/disks/gcs
          mountPropagation: Bidirectional
        - name: config
          mountPath: /config
        - name: secrets
          mountPath: /secrets
        lifecycle:
          preStop:
            exec:
               command: ["sh", "-c", "fusermount -u /mnt/disks/gcs"]
      volumes:
      - name: mnt-disks-gcs
        hostPath:
          path: /mnt/disks/gcs
      - name: config
        configMap:
          name: gcsfuse-config
      - name: secrets
        secret:
          secretName: gcsfuse-secrets
          defaultMode: 0444
