apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "xss-bot"
  namespace: "default"
  labels:
    app: "xss-bot"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "xss-bot"
  template:
    metadata:
      labels:
        app: "xss-bot"
      annotations:
        container.apparmor.security.beta.kubernetes.io/challenge: localhost/ctf-profile
    spec:
      containers:
      - name: "challenge"
        # this will be updated to eu.gcr.io/$project/$challenge-dir using kustomization.yaml in the kctf-conf
        image: "xss-bot"
        ports:
        - containerPort: 1337
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
          readOnlyRootFilesystem: true
        command:
        resources:
          limits:
            cpu: "0.9"
          requests:
            cpu: "0.45"
        volumeMounts:
        - name: "secrets"
          mountPath: "/secrets"
          readOnly: true
        - name: "config"
          mountPath: "/config"
          readOnly: true
        - name: "tmp"
          mountPath: "/tmp"
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 3
          periodSeconds: 30
      - name: "healthcheck"
        image: "xss-bot-healthcheck"
        command:
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.05"
        volumeMounts:
        - name: "healthcheck-secrets"
          mountPath: "/secrets"
          readOnly: true
        - name: "healthcheck-exploit-key"
          mountPath: "/keys"
          readOnly: true
        - name: "healthcheck-config"
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: "secrets"
        secret:
          # must be called ${challenge-dir}-secrets
          secretName: "xss-bot-secrets"
          defaultMode: 0444
      - name: "config"
        configMap:
          # must be called ${challenge-dir}-config
          name: "xss-bot-config"
      - name: "healthcheck-secrets"
        secret:
          # must be called ${challenge-dir}-healthcheck-secrets
          secretName: "xss-bot-healthcheck-secrets"
          defaultMode: 0444
      - name: "healthcheck-exploit-key"
        secret:
          # must be called ${challenge-dir}-healthcheck-exploit-key
          secretName: "xss-bot-healthcheck-exploit-key"
          defaultMode: 0444
      - name: "healthcheck-config"
        configMap:
          # must be called ${challenge-dir}-healthcheck-config
          name: "xss-bot-healthcheck-config"
      - name: "tmp"
        emptyDir:
          medium: "Memory"
