# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kctf.dev/v1
kind: ChallengeInstanceTemplate
metadata:
  name: misc-fishmaze
spec:
  domainName: "fishmaze.instancer.2025.ctfcompetition.com"
  gatewayName: "instancer-challenge-gateway"
  defaultDuration: 600
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        targetPort: 3000
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: europe-west4-docker.pkg.dev/gctf-2025/gctf-2025-kctf-managed-challenges/misc-fishmaze-healthcheck:949c64c21a71693e3d2bf92f14ed6c1d897800a7b5370e411dda71cc87716746
  image: europe-west4-docker.pkg.dev/gctf-2025/gctf-2025-kctf-managed-challenges/misc-fishmaze-challenge:8ba22c8add85ae83f87b4b0722f3144aa959246469dd56e1229114e2bc58c5eb
  horizontalPodAutoscalerSpec:
    maxReplicas: 20
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - name: tmp
                mountPath: /tmp
            resources:
              requests:
                cpu: "0.5"
                memory: "512Mi"
        volumes:
          - name: tmp
            emptyDir:
              medium: Memory
              sizeLimit: 64Mi
        runtimeClassName: kata-qemu
        nodeSelector:
          nested-virtualization: enabled
