apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "chal"
spec:
  template:
    spec:
      containers:
      - name: challenge
        volumeMounts:
        - name: sessions
          mountPath: /mnt/disks/sessions
        - name: uploads
          mountPath: /mnt/disks/uploads
      volumes:
      - name: sessions
        hostPath:
          path: /mnt/disks/gcs/apache-php/sessions
      - name: uploads
        hostPath:
          path: /mnt/disks/gcs/apache-php/uploads
