apiVersion: "autoscaling/v1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "challenge-skeleton-hpa"
  namespace: "default"
  labels:
    app: "challenge-skeleton"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "challenge-skeleton"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
