apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: kctf
spec:
  deployed: true
  powDifficultySeconds: 1
  network:
    public: true
  healthcheck:
    enabled: true
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            volumeMounts:
              - mountPath: /flag
                name: flag
                readOnly: true
              - name: etc-os-release
                mountPath: /etc/node-os-release
        volumes:
          - name: etc-os-release
            hostPath:
              path: /etc/os-release
        volumes:
          - name: flag
            secret:
              defaultMode: 0555
              secretName: kctf-flag
              optional: true
